config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet/fedcloudclient:
      branch: master
      repo: https://github.com/tdviet/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.ruby_carefree_unicorn.sh
        container: qc.acc_dahlia_thoughtful_warthog
  QC.Doc:
    repos:
      github.com/tdviet/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.navy_hardworking_alpaca.sh
        container: qc.doc_ruby_anxious_ferret
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_sociable_mink.sh
        container: qc.doc_storm_practical_phoenix
      github.com/tdviet/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.butterscotch_wise_lynx.sh
        container: qc.doc_cobalt_fearless_baboon
      github.com/tdviet/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.mahogany_alert_dingo.sh
        container: qc.doc_cornflower_authentic_seahorse
  QC.Lic:
    repos:
      github.com/tdviet/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.celadon_funny_lemur.sh
        container: qc.lic_arctic_audacious_meerkat
  QC.Sec:
    repos:
      github.com/tdviet/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.plum_outgoing_mink.sh
        container: qc.sec_aquamarine_focused_ibex
  QC.Sty:
    repos:
      github.com/tdviet/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ceru_agile_chimpanzee.sh
        container: qc.sty_ultramarine_resilient_penguin
      github.com/tdviet/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_delighted_starfish.sh
        container: qc.sty_malachite_adaptable_dhole
      github.com/tdviet/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flax_ambitious_ocelot.sh
        container: qc.sty_crimson_rugged_shark
  QC.Uni:
    repos:
      github.com/tdviet/fedcloudclient pytest:
        commands:
        - /usr/bin/env sh .sqa/script.caramel_feisty_otter.sh
        container: qc.uni_avocado_agile_nymph
  QC.Ver:
    repos:
      github.com/tdviet/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.reef_daring_leopard.sh
        container: qc.ver_sunset_curious_albatross
timeout: 5400
