config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet4free/fedcloudclient:
      branch: sqaaas-test
      repo: https://github.com/tdviet4free/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-blue-mandrill.sh
        container: qc.acc_crabby-gold-ocelot
  QC.Doc:
    repos:
      github.com/tdviet4free/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-black-spoonbill.sh
        container: qc.doc_wimpy-cerulean-cuttlefish
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-bronze-chinchilla.sh
        container: qc.doc_jumpy-russet-audemer
      github.com/tdviet4free/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-saffron-donkey.sh
        container: qc.doc_cheeky-olivine-balinese
      github.com/tdviet4free/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-peach-chicken.sh
        container: qc.doc_gloppy-lemon-cow
  QC.Lic:
    repos:
      github.com/tdviet4free/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-smalt-blue.sh
        container: qc.lic_surly-chartreuse-kangaroo
  QC.Met:
    repos:
      github.com/tdviet4free/fedcloudclient validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ecru-coral.sh
        container: qc.met_surly-heliotrope-chinook
  QC.Sec:
    repos:
      github.com/tdviet4free/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-apricot-tetra.sh
        container: qc.sec_wiggy-ecru-dolphin
  QC.Sty:
    repos:
      github.com/tdviet4free/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cyan-sheep.sh
        container: qc.sty_stuffy-sepia-monkey
      github.com/tdviet4free/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-jade-dhole.sh
        container: qc.sty_craggy-wheat-chipmunk
      github.com/tdviet4free/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ecru-bee.sh
        container: qc.sty_sleepy-turquoise-malamute
  QC.Ver:
    repos:
      github.com/tdviet4free/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-asparagus-dhole.sh
        container: qc.ver_whiny-vermilion-snail
timeout: 5400
